version: "3.8"

services:
  eureka-server:
    build: .
    container_name: EurekaServer
    ports:
      - "8761:8761"
    environment:
      PORT: 8761
    command: ["java", "-jar","/eurekaServer.jar"]
    networks:
      - micro-net
networks:
  micro-net:
    name: micro-net
    external: true