version: "3.8"


services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=1024
      - MYSQL_DATABASE=loginauth
    ports:
      - "3307:3306"
    volumes:
      - ./db:/var/lib/mysql
