version: "3.8"

services:
  image:
    build: .
    container_name: ImageService
    ports:
      - "8200:8200"
    environment:
      PORT: 8200
    command: ["java", "-jar","/imageService.jar"]
    networks:
      - micro-net
networks:
  micro-net:
    name: micro-net
    external: true