server:
  port: 8762

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://host.docker.internal:8761/eureka/

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: gallery-service
          uri: http://host.docker.internal:8100/gallery
#          uri: http://localhost:8100/gallery
          predicates:
            - Path=/gallery/**

        - id: auth-service
          uri: http://host.docker.internal:9100/auth
#          uri: http://localhost:9100/auth
          predicates:
            - Path=/auth/**