version: "3.8"

services:
  gallery:
    build: .
    container_name: GalleryService
    ports:
      - "8100:8100"
    environment:
      PORT: 8100
    command: ["java", "-jar","/galleryService.jar"]
    networks:
      - micro-net
networks:
  micro-net:
    name: micro-net
    external: true