
#spring.application.name=gallery-service
#server.port=8100
#eureka.client.service-url.default-zone=http://host.docker.internal:8761/eureka
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true

server:
  port: 8100

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://host.docker.internal:8761/eureka/

spring:
  application:
    name: gallery-service