#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/loginauth
#spring.datasource.username=root
#spring.datasource.password=1024
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
## App Properties
#linh.app.jwtSecret= ======================llu1ts===========================
#linh.app.jwtExpirationMs= 3600000
#linh.app.jwtRefreshExpirationMs= 86400000
#
#
#
#spring.application.name=auth-service
#
#server.port=9100
#
#eureka.client.service-url.default-zone=http://localhost:8761/eureka

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/loginauth
    username: root
    password: 1024
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: auth-service
server:
  port: 9100
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

linh:
  app:
    jwtSecret: ======================llu1ts===========================
    jwtExpirationMs: 3600000
    jwtRefreshExpirationMs: 86400000