server:
  port: 8200

eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://eureka-server:8761/eureka/
      defaultZone: http://host.docker.internal:8761/eureka/

spring:
  application:
    name: image-service