version: "3.8"  # Current version as of March 1, 2024

services:
  auth-service:
    build: .
    container_name: AuthService
    ports:
      - "9100:9100"
    environment:
      PORT: 9100
#      Same thing with 3307
#      SPRING_APPLICATION_JSON: '{
#            "spring.datasource.url"  : "jdbc:mysql://mysqldb:3307/loginauth",
#            "spring.datasource.username" : "root",
#            "spring.datasource.password" : "1024",
#            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
#            "spring.jpa.hibernate.ddl-auto" : "update"
#          }'
    command: ["java", "-jar","/authService.jar"]
    networks:
      - micro-net
networks:
  micro-net:
    name: micro-net
    external: true